export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const REQUEST_CHARACTERS_ERROR = 'REQUEST_CHARACTERS_ERROR';
